version: '2'
services:
  redis:
    image: "redis:4.0.1"
  postgres:
    image: "postgres:9.6.5"
    environment:
     POSTGRES_PASSWORD: password
     POSTGRES_USER: user
     POSTGRES_DB: no-line
  web:
    build: .
    ports:
     - "80:3000"
    volumes:
     - .:/usr/src/app
    depends_on:
      - postgres
      - redis
    command: ["./wait_for_it.sh", "postgres:5432", "--", "npm", "start"]